wandb_version: 1

seed:
  desc: null
  value: 0
epochs:
  desc: null
  value: 10
model:
  desc: null
  value: google/flan-t5-large
output_dir:
  desc: null
  value: ./models
train:
  desc: null
  value: true
train_batch_size:
  desc: null
  value: 2
debug:
  desc: null
  value: false
eval_steps:
  desc: null
  value: 200
accum:
  desc: null
  value: 8
overwrite_cache:
  desc: null
  value: true
max_source_length:
  desc: null
  value: 1024
max_target_length:
  desc: null
  value: 256
_wandb:
  desc: null
  value:
    python_version: 3.9.13
    cli_version: 0.15.0
    framework: huggingface
    huggingface_version: 4.26.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1682146466.217415
    t:
      1:
      - 11
      - 49
      - 51
      - 55
      2:
      - 11
      - 49
      - 51
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.9.13
      5: 0.15.0
      6: 4.26.1
      8:
      - 5
